use multiversx_chain_core::std::Bech32Hrp;
use multiversx_sdk::{
    crypto::{private_key::PrivateKey, public_key::PublicKey},
    wallet::{Keystore, KeystoreError, KeystoreRandomness, WalletSource},
};

// Well-known Alice private key used across the test suite.
const ALICE_PRIVATE_KEY_HEX: &str =
    "413f42575f7f26fad3317a778771212fdb80245850981e48b58a4f25e344e8f9";
const KEYSTORE_PASSWORD: &str = "test_password";

/// Fully deterministic randomness: all-zeroes salt, all-ones IV, fixed UUID.
fn fixed_randomness() -> KeystoreRandomness {
    KeystoreRandomness {
        salt: [0u8; 32],
        iv: [1u8; 16],
        id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890".to_string(),
    }
}

fn alice_private_key() -> PrivateKey {
    PrivateKey::from_hex_str(ALICE_PRIVATE_KEY_HEX).unwrap()
}

fn erd_hrp() -> Bech32Hrp {
    Bech32Hrp::try_from("erd").unwrap()
}

// ---------------------------------------------------------------------------
// Encrypt / decrypt
// ---------------------------------------------------------------------------

#[test]
fn test_keystore_encrypt_decrypt_roundtrip() {
    let private_key = alice_private_key();
    let keystore = Keystore::encrypt(
        private_key,
        erd_hrp(),
        KEYSTORE_PASSWORD,
        fixed_randomness(),
    );

    let wallet = keystore.decrypt_wallet(KEYSTORE_PASSWORD).unwrap();

    assert_eq!(wallet.private_key, private_key);
    assert_eq!(
        wallet.source,
        WalletSource::Keystore(Bech32Hrp::try_from("erd").unwrap())
    );
    assert_eq!(wallet.address, PublicKey::from(&private_key).to_address(),);
}

#[test]
fn test_keystore_wrong_password_rejected() {
    let keystore = Keystore::encrypt(
        alice_private_key(),
        erd_hrp(),
        KEYSTORE_PASSWORD,
        fixed_randomness(),
    );

    assert!(matches!(
        keystore.decrypt_wallet("wrong_password"),
        Err(KeystoreError::InvalidPassword)
    ));
}

// ---------------------------------------------------------------------------
// Serialization / deserialization
// ---------------------------------------------------------------------------

#[test]
fn test_keystore_serialize_deserialize_roundtrip() {
    let private_key = alice_private_key();
    let keystore = Keystore::encrypt(
        private_key,
        erd_hrp(),
        KEYSTORE_PASSWORD,
        fixed_randomness(),
    );

    let json = keystore.to_json_string();

    let keystore2: Keystore = Keystore::from_json(serde_json::from_str(&json).unwrap()).unwrap();
    let wallet = keystore2.decrypt_wallet(KEYSTORE_PASSWORD).unwrap();

    assert_eq!(wallet.private_key, private_key);
}

#[test]
fn test_keystore_json_snapshot() {
    let keystore = Keystore::encrypt(
        alice_private_key(),
        erd_hrp(),
        KEYSTORE_PASSWORD,
        fixed_randomness(),
    );

    let json = keystore.to_json_string();

    assert_eq!(json, EXPECTED_KEYSTORE_JSON);
}

#[test]
fn test_full_encrypt_serialize_deserialize_decrypt_sign() {
    const MESSAGE: &[u8] = b"hello multiversx";

    // Encrypt.
    let keystore = Keystore::encrypt(
        alice_private_key(),
        erd_hrp(),
        KEYSTORE_PASSWORD,
        fixed_randomness(),
    );

    // Serialize to JSON, then deserialize back.
    let json = keystore.to_json_string();
    let keystore2 = Keystore::from_json(serde_json::from_str(&json).unwrap()).unwrap();

    // Decrypt into a Wallet.
    let wallet = keystore2.decrypt_wallet(KEYSTORE_PASSWORD).unwrap();
    assert_eq!(wallet.private_key, alice_private_key());

    // Sign the message.
    let sig = wallet.sign_bytes(MESSAGE);

    // Ed25519 is deterministic: same key + same message always gives the same signature.
    assert_eq!(sig, wallet.sign_bytes(MESSAGE));

    // Snapshot: exact signature bytes must match.
    assert_eq!(hex::encode(sig), EXPECTED_SIGNATURE_HEX);
}

// Generated by running the test suite once with fixed randomness.
const EXPECTED_KEYSTORE_JSON: &str = r#"{
  "version": 4,
  "kind": "secretKey",
  "id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
  "address": "0139472eff6886771a982f3083da5d421f24c29181e63888228dc81ca60d69e1",
  "bech32": "erd1qyu5wthldzr8wx5c9ucg8kjagg0jfs53s8nr3zpz3hypefsdd8ssycr6th",
  "crypto": {
    "ciphertext": "66f761de7f386c3cde5d8b1650c37614263880e96314b3070c45a39e44eb7b46573174ddade22c2a5f7dae73385d5a0abc5cff566e34152867c0ff560f1d5d05",
    "cipherparams": {
      "iv": "01010101010101010101010101010101"
    },
    "cipher": "aes-128-ctr",
    "kdf": "scrypt",
    "kdfparams": {
      "dklen": 32,
      "salt": "0000000000000000000000000000000000000000000000000000000000000000",
      "n": 4096,
      "r": 8,
      "p": 1
    },
    "mac": "4f9db1601de9013e32b2a8ca6cd941b5f5a3feb7a592c0b2586f6b8c1b2a87b9"
  }
}
"#;

const EXPECTED_SIGNATURE_HEX: &str = "c32f811c809a02d3548f190b134d5fa542b028935f4e300556e29b3164f146d54aa7e37ba97080e9f72402af67f6f6f070cbbd1b496c9779e75038a6aee54c07";
