// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            8
// Async Callback:                       1
// Promise callbacks:                    1
// Total number of exported functions:  11

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    forwarder_blind
    (
        init => init
        blind_async_v1 => blind_async_v1
        blind_async_v2 => blind_async_v2
        blind_deploy => blind_deploy
        blind_sync => blind_sync
        blind_sync_fallible => blind_sync_fallible
        blind_transf_exec => blind_transf_exec
        blind_upgrade => blind_upgrade
        blind_upgrade_from_source => blind_upgrade_from_source
        blind_async_v2_callback => blind_async_v2_callback
    )
}

multiversx_sc_wasm_adapter::async_callback! { forwarder_blind }
