// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           60
// Async Callback:                       1
// Total number of exported functions:  62

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    use_module
    (
        checkFeatureGuard
        checkPause
        call_mod_a
        call_mod_b
        call_mod_c
        only_owner_mod_endpoint
        call_derived_not_owner_only
        only_admin_mod_endpoint
        call_derived_not_admin_only
        countTo100
        mergeTokens
        mergeTokensCustomAttributes
        splitTokens
        splitTokenPartial
        claimDeveloperRewards
        dnsRegister
        issueToken
        setFeatureFlag
        depositTokensForProposal
        withdrawGovernanceTokens
        propose
        vote
        queue
        execute
        cancel
        getProposalStatus
        getProposer
        getProposalDescription
        getProposalActions
        getProposalVotes
        getTotalVotes
        getTotalDownvotes
        changeQuorum
        changeMinTokenBalanceForProposing
        changeVotingDelayInBlocks
        changeVotingPeriodInBlocks
        changeLockTimeAfterVotingEndsInBlocks
        getGovernanceTokenId
        getQuorum
        getMinFeeForPropose
        getMinTokenBalanceForProposing
        getVotingDelayInBlocks
        getVotingPeriodInBlocks
        getLockTimeAfterVotingEndsInBlocks
        pause
        unpause
        isPaused
        stake
        unstake
        voteSlashMember
        slashMember
        issueMergedToken
        addMergeableTokensToWhitelist
        removeMergeableTokensFromWhitelist
        getMergedTokenId
        getMergeableTokensWhitelist
        isAdmin
        addAdmin
        removeAdmin
        getAdmins
        callBack
    )
}
