// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Number of endpoints: 7

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    lottery_esdt
    (
        start
        createLotteryPool
        buy_ticket
        determine_winner
        status
        getLotteryInfo
        getLotteryWhitelist
    )
}

elrond_wasm_node::wasm_empty_callback! {}
