use std::{fs, fs::File, io::Write};

use abi_tester::abi_tester_full_abi::AbiProvider;
use multiversx_sc::abi::ContractAbiProvider;
use multiversx_sc_meta_lib::abi_json::{ContractAbiJson, serialize_abi_to_json};

/// Framework-agnostic ABI description of the full `abi-tester` contract interface
/// (`contracts/feature-tests/abi-tester/src/abi_tester.rs`), generated by the `[[proxy]]`
/// `format = "abi"` mechanism (`contracts/feature-tests/abi-tester/src/abi_tester_full_abi.rs`)
/// and re-derived here purely from its `#[contract_abi]`-annotated trait, with no dependency on
/// `multiversx-sc`/`VMApi`.
#[test]
fn abi_tester_spec_abi_generated_ok() {
    let abi = AbiProvider::abi();
    let abi_json = ContractAbiJson::from(&abi);
    let abi_string = serialize_abi_to_json(&abi_json);

    // save generated ABI to disk for easier comparison in case something is off
    let mut file = File::create("abi_tester_spec_generated.abi.json").unwrap();
    file.write_all(abi_string.as_bytes()).unwrap();

    // load expected from disk & check!
    assert_eq!(
        abi_string,
        fs::read_to_string("./abi_tester_spec_expected.abi.json").unwrap()
    );
}
