use std::{
    collections::{HashSet, VecDeque},
    fmt::Display,
};

use multiversx_sc::abi::{
    EndpointAbi, EndpointMutabilityAbi, EndpointTypeAbi, EnumVariantDescription, OutputAbi,
    StructFieldDescription, TypeContents, TypeDescription, TypeNames,
};

use crate::contract::sc_config::proxy_config::ProxyConfig;

use super::proxy_process_type_name::{
    c_enum_representation, explicit_discriminant, extract_paths, process_rust_type,
};

const ZERO: &str = "0";

const PRELUDE: &str = "// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]
";

/// The pure-ABI-typed source shapes `[[proxy]] format` can produce, alongside the legacy
/// `TxProxyTrait`-based `ProxyGenerator` output (`format = "proxy"`, the default, untouched).
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum AbiSourceMode {
    /// A `#[multiversx_sc_abi::contract_abi(call = ...)]`-annotated trait: the *input*
    /// the macro consumes.
    Trait,
    /// The raw `AbiProxyTrait`/`ProxyArg`/`IntoXxx` implementation, hand-writable style (see
    /// `contracts/feature-tests/abi-tester/src/abi_tester_full_abi_raw.rs`): what that macro
    /// *expands to*.
    Raw,
}

/// Generates framework-agnostic ABI source (see `AbiSourceMode`) from a `ContractAbi`, mirroring
/// `ProxyGenerator`'s structure but targeting `multiversx_sc_abi`'s `AbiProxyTrait` family
/// instead of the legacy `TxProxyTrait` one.
///
/// Type names are resolved via `TypeNames::pure_rust` (`<T::Abi as TypeAbi>::type_name_rust()`,
/// computed once at compile time when the original contract's ABI was built) for framework
/// types, and via the bare `TypeNames::abi` name for local custom struct/enum types, each of
/// which gets its own local, non-generic, pure-typed definition emitted by `write_types`.
pub struct AbiSourceGenerator<'a> {
    pub file: Option<&'a mut dyn std::io::Write>,
    pub proxy_config: &'a ProxyConfig,
    pub mode: AbiSourceMode,
}

impl<'a> AbiSourceGenerator<'a> {
    pub fn new(
        file: &'a mut dyn std::io::Write,
        proxy_config: &'a ProxyConfig,
        mode: AbiSourceMode,
    ) -> Self {
        Self {
            file: Some(file),
            proxy_config,
            mode,
        }
    }

    fn write(&mut self, s: impl Display) {
        let file = self.file.as_mut().unwrap();
        file.write_all(s.to_string().as_bytes()).unwrap();
    }

    fn writeln(&mut self, s: impl Display) {
        self.write(s);
        self.write("\n");
    }

    pub fn write_to_file(&mut self) {
        self.write_header();
        self.write_types();
        match self.mode {
            AbiSourceMode::Trait => self.write_trait(),
            AbiSourceMode::Raw => self.write_raw(),
        }
    }

    fn write_header(&mut self) {
        self.writeln(PRELUDE);

        if !self.proxy_config.override_import.is_empty() {
            self.writeln(self.proxy_config.override_import.to_owned());
            return;
        }

        // The primary source for everything this file needs - the ABI marker types (`BigUintAbi`,
        // `Address`, ...), `AbiProxyTrait`/`ProxyArg`/`IntoXxx`, the codec traits, and the
        // `#[multiversx_sc_abi::contract_abi(...)]` macro - kept deliberately free of any `multiversx-sc`/`VMApi`
        // dependency. A glob import costs nothing when a mode/file doesn't end up using part of
        // it (e.g. `contract_abi` in Raw mode).
        self.writeln("use multiversx_sc_abi::imports::*;");
    }

    /// Resolves an ABI type reference to a pure Rust type name: the bare local name for a
    /// custom struct/enum this generator is about to emit a definition for (see `write_types`),
    /// otherwise the compile-time-computed `pure_rust` name (already fully resolved and
    /// correct, recursively, for every framework managed type).
    ///
    /// `pure_rust` is correct at the leaf level, but for a *composite* type (`Option<T>`,
    /// tuples, `MultiValueN<...>`, ...) wrapping a local custom struct/enum, the embedded
    /// inner type name is `T`'s own `type_name_rust()` — for a custom type that's always the
    /// full `core::any::type_name` path (`#[type_abi]` never overrides it), since only the
    /// *outer* wrapper's `Abi` projection ran, not a projection of the inner type itself. So
    /// every occurrence still needs the same local-path-stripping pass `clean_local_paths`
    /// applies to the whole string, exactly mirroring what `ProxyGenerator::clean_paths` does
    /// for `.rust` names.
    fn abi_type(&self, type_names: &TypeNames) -> String {
        if let Some(resolved) = self.resolve_local_type(&type_names.abi, &type_names.rust) {
            return resolved;
        }
        self.clean_local_paths(&type_names.abi_rust)
    }

    /// If `abi_name` denotes a type this generator would otherwise define locally (see
    /// `write_types` — a described struct/enum with actual contents), resolves it to whichever
    /// applies: the `path_rename` target configured for it (see `path_rename_for`), or, if none
    /// applies, its own bare local name (the definition `write_types` emits for it).
    fn resolve_local_type(&self, abi_name: &str, rust_name: &str) -> Option<String> {
        let desc = self.proxy_config.abi.type_descriptions.find(abi_name)?;
        if !desc.contents.is_specified() {
            return None;
        }
        Some(
            self.path_rename_for(abi_name, rust_name)
                .unwrap_or_else(|| abi_name.to_string()),
        )
    }

    /// Resolves the configured `path-rename` target for a locally-described type, if any applies.
    ///
    /// Tried in order:
    /// 1. `path_rename.from` against the type's own bare ABI name (the preferred, stable form -
    ///    e.g. `"MyStruct"`); on a hit, `path_rename.to` is the *whole* replacement path, since an
    ///    ABI name identifies the type unambiguously.
    /// 2. The legacy match: `path_rename.from` contained anywhere in `rust_name` (typically a
    ///    crate or module prefix, e.g. `"my_crate::my_mod"`); on a hit, only that substring is
    ///    spliced out for `path_rename.to`, keeping the rest of `rust_name` (e.g. the trailing
    ///    struct name) intact — kept for configs still written the old way.
    fn path_rename_for(&self, abi_name: &str, rust_name: &str) -> Option<String> {
        if let Some(pr) = self
            .proxy_config
            .path_rename
            .iter()
            .find(|pr| pr.from == abi_name)
        {
            return Some(pr.to.clone());
        }

        self.proxy_config
            .path_rename
            .iter()
            .find(|pr| rust_name.contains(pr.from.as_str()))
            .map(|pr| rust_name.replacen(pr.from.as_str(), pr.to.as_str(), 1))
    }

    /// Strips every embedded path down to its resolved local reference (bare name, or its
    /// `path_rename` target) when that name is one of our own local types (see `write_types`) —
    /// the same technique `ProxyGenerator::clean_paths` uses for `.rust` names, applied to
    /// `pure_rust` strings instead. Paths that aren't local types (external crates, or a residual
    /// `$API`/`UncallableApi` placeholder left over from a managed type with no registered pure
    /// ABI equivalent) are left untouched.
    fn clean_local_paths(&self, rust_type: &str) -> String {
        let paths = extract_paths(rust_type);
        let processed_paths: Vec<String> = paths
            .iter()
            .map(|path| {
                let bare_name = path.rsplit("::").next().unwrap_or(path);
                self.resolve_local_type(bare_name, path)
                    .unwrap_or_else(|| path.clone())
            })
            .collect();
        process_rust_type(rust_type.to_string(), paths, processed_paths)
    }

    // ---- exported functions (constructors / upgrades / endpoints) ----

    /// Takes `proxy_config` directly (rather than `&self`) so the returned borrow is tied to
    /// `'a` (the `ProxyConfig` reference's own lifetime) instead of to a `&self` call — letting
    /// callers iterate the result while still holding `&mut self` for `write_trait_method`/
    /// `write_raw_method`.
    fn exported_endpoints(proxy_config: &'a ProxyConfig) -> Vec<&'a EndpointAbi> {
        proxy_config
            .abi
            .constructors
            .iter()
            .chain(proxy_config.abi.upgrade_constructors.iter())
            .chain(proxy_config.abi.endpoints.iter())
            .collect()
    }

    fn output_type(&self, outputs: &[OutputAbi]) -> String {
        match outputs.len() {
            0 => "()".to_string(),
            1 => self.abi_type(&outputs[0].type_names),
            _ => {
                let inner: Vec<String> = outputs
                    .iter()
                    .map(|o| self.abi_type(&o.type_names))
                    .collect();
                format!("MultiValue{}<{}>", outputs.len(), inner.join(", "))
            }
        }
    }

    // ---- Trait mode ----

    fn write_trait(&mut self) {
        // Only pass `call = ...` when the config actually asked for a call proxy to be
        // generated (`[[generate-abi]] call = "..."`) - without it, `#[multiversx_sc_abi::contract_abi]` on its own
        // still generates the `AbiProvider` impl, just no `ProxyName`/`ProxyNameMethods` proxy.
        let contract_abi_attr = match &self.proxy_config.call_name {
            Some(call_name) => format!("#[multiversx_sc_abi::contract_abi(call = {call_name})]"),
            None => "#[multiversx_sc_abi::contract_abi]".to_owned(),
        };
        self.writeln(format!(
            "\n#[rustfmt::skip]\n{contract_abi_attr}\npub trait {} {{",
            self.proxy_config.abi.name
        ));

        for endpoint in Self::exported_endpoints(self.proxy_config) {
            self.write_trait_method(endpoint);
        }

        self.writeln("}");
    }

    fn write_trait_method(&mut self, endpoint: &EndpointAbi) {
        for doc in &endpoint.docs {
            self.writeln(format!("    /// {doc}"));
        }
        if endpoint.allow_multiple_var_args {
            self.writeln("    #[allow_multiple_var_args]");
        }
        if endpoint.only_owner {
            self.writeln("    #[only_owner]");
        }
        if endpoint.only_admin {
            self.writeln("    #[only_admin]");
        }
        for token in &endpoint.payable_in_tokens {
            self.writeln(format!("    #[payable(\"{token}\")]"));
        }
        self.writeln(match endpoint.endpoint_type {
            EndpointTypeAbi::Init => "    #[init]".to_string(),
            EndpointTypeAbi::Upgrade => "    #[upgrade]".to_string(),
            EndpointTypeAbi::PromisesCallback => return, // no external call surface
            EndpointTypeAbi::Endpoint => match endpoint.mutability {
                EndpointMutabilityAbi::Readonly | EndpointMutabilityAbi::Pure => {
                    format!("    #[view({})]", endpoint.name)
                }
                EndpointMutabilityAbi::Mutable => format!("    #[endpoint({})]", endpoint.name),
            },
        });

        let args: Vec<String> = endpoint
            .inputs
            .iter()
            .map(|input| format!("{}: {}", input.arg_name, self.abi_type(&input.type_names)))
            .collect();

        let return_part = if endpoint.outputs.is_empty() {
            String::new()
        } else {
            format!(" -> {}", self.output_type(&endpoint.outputs))
        };

        self.writeln(format!(
            "    fn {}(&self{}{}){};\n",
            endpoint.rust_method_name,
            if args.is_empty() { "" } else { ", " },
            args.join(", "),
            return_part
        ));
    }

    // ---- Raw mode ----

    fn write_raw(&mut self) {
        let proxy_name =
            super::proxy_process_type_name::proxy_type_name(&self.proxy_config.abi.name);
        let methods_name =
            super::proxy_process_type_name::proxy_methods_type_name(&self.proxy_config.abi.name);

        self.writeln(format!("pub struct {proxy_name};\n"));
        self.writeln(format!(
            "#[rustfmt::skip]\nimpl<T> AbiProxyTrait<T> for {proxy_name} {{\n    type Methods = {methods_name}<T>;\n\n    fn proxy_methods(self, base_tx: T) -> Self::Methods {{\n        {methods_name} {{ base_tx }}\n    }}\n}}\n"
        ));
        self.writeln(format!(
            "pub struct {methods_name}<T> {{\n    base_tx: T,\n}}"
        ));

        for endpoint in Self::exported_endpoints(self.proxy_config) {
            self.write_raw_method(endpoint, &methods_name);
        }
    }

    fn write_raw_method(&mut self, endpoint: &EndpointAbi, methods_name: &str) {
        if matches!(endpoint.endpoint_type, EndpointTypeAbi::PromisesCallback) {
            return; // no external call surface
        }

        let payable = !endpoint.payable_in_tokens.is_empty();
        let output_ty = self.output_type(&endpoint.outputs);

        let (into_trait, into_method, extra_generic, payment_param, call_args): (
            String,
            &str,
            &str,
            &str,
            String,
        ) = match endpoint.endpoint_type {
            EndpointTypeAbi::Init => (
                format!(
                    "IntoDeploy<{}, {output_ty}>",
                    if payable { "Payment" } else { "NotPayable" }
                ),
                "into_deploy",
                if payable { "Payment, " } else { "" },
                if payable { "payment: Payment, " } else { "" },
                (if payable { "payment" } else { "NotPayable" }).to_string(),
            ),
            EndpointTypeAbi::Upgrade => (
                format!(
                    "IntoUpgrade<{}, {output_ty}>",
                    if payable { "Payment" } else { "NotPayable" }
                ),
                "into_upgrade",
                if payable { "Payment, " } else { "" },
                if payable { "payment: Payment, " } else { "" },
                (if payable { "payment" } else { "NotPayable" }).to_string(),
            ),
            EndpointTypeAbi::Endpoint => (
                format!(
                    "IntoCall<{}, {output_ty}>",
                    if payable { "Payment" } else { "NotPayable" }
                ),
                "into_call",
                if payable { "Payment, " } else { "" },
                if payable { "payment: Payment, " } else { "" },
                format!(
                    "{}, \"{}\"",
                    if payable { "payment" } else { "NotPayable" },
                    endpoint.name
                ),
            ),
            EndpointTypeAbi::PromisesCallback => unreachable!(),
        };

        let arg_generics: Vec<String> = endpoint
            .inputs
            .iter()
            .enumerate()
            .map(|(i, input)| format!("Arg{i}: ProxyArg<{}>", self.abi_type(&input.type_names)))
            .collect();
        let arg_params: Vec<String> = endpoint
            .inputs
            .iter()
            .enumerate()
            .map(|(i, input)| format!("{}: Arg{i}", input.arg_name))
            .collect();
        let apply_args: String = endpoint
            .inputs
            .iter()
            .map(|input| format!("\n            .apply_argument(&{})", input.arg_name))
            .collect();

        self.writeln(format!(
            "\n#[rustfmt::skip]\nimpl<T> {methods_name}<T> {{\n    pub fn {}<{extra_generic}{}>(\n        self,\n        {payment_param}{}\n    ) -> <T as {into_trait}>::Out\n    where\n        T: {into_trait},\n    {{\n        self.base_tx\n            .{into_method}({call_args}){apply_args}\n    }}\n}}",
            endpoint.rust_method_name,
            arg_generics.join(", "),
            arg_params.join(", "),
        ));
    }

    // ---- local type definitions (structs / enums), shared by both modes ----

    fn write_types(&mut self) {
        let reachable = self.reachable_local_abi_names();

        let type_descriptions = self.proxy_config.abi.type_descriptions.0.clone();
        for (_, type_description) in &type_descriptions {
            if !type_description.contents.is_specified() {
                continue;
            }
            let abi_name = type_description.names.abi.as_str();
            if !reachable.contains(abi_name) {
                continue;
            }

            let name = type_description.names.abi.clone();
            match &type_description.contents {
                TypeContents::Enum(variants) => self.write_enum(variants, type_description, &name),
                TypeContents::Struct(fields) => self.write_struct(fields, type_description, &name),
                TypeContents::ExplicitEnum(_) | TypeContents::NotSpecified => {}
            }
        }
    }

    /// Every locally-described type this generator must define, i.e. every type reachable from
    /// the exported endpoints' inputs/outputs, event inputs, and `#[esdt_attribute]` types, by
    /// following struct fields/enum variant fields transitively — *except* the traversal stops at
    /// (and never emits) a type that `path_rename_for` redirects elsewhere: whatever shape it has
    /// doesn't belong to this file anymore, so its own field types must not be pulled in on its
    /// account either. Without this, a struct that's ONLY ever reachable through a renamed type
    /// (e.g. `Color`, reachable only through a renamed `Kitty`) would still get emitted here as
    /// orphaned, unreferenced dead code.
    ///
    /// Driven by a queue of not-yet-examined type-name strings: each one is broken into candidate
    /// bare names (`top_level_abi_candidates`) and resolved straight against the full
    /// `TypeDescription`s already sitting in `type_descriptions` - no separate bookkeeping of
    /// "types found so far" beyond the `reachable` set itself, since that container already knows
    /// every locally-described type there is.
    fn reachable_local_abi_names(&self) -> HashSet<String> {
        let mut reachable = HashSet::new();
        let mut queue: VecDeque<String> = VecDeque::new();

        for endpoint in Self::exported_endpoints(self.proxy_config) {
            queue.extend(
                endpoint
                    .inputs
                    .iter()
                    .map(|i| i.type_names.abi_rust.clone()),
            );
            queue.extend(
                endpoint
                    .outputs
                    .iter()
                    .map(|o| o.type_names.abi_rust.clone()),
            );
        }
        for event in &self.proxy_config.abi.events {
            queue.extend(event.inputs.iter().map(|i| i.type_name.clone()));
        }
        queue.extend(
            self.proxy_config
                .abi
                .esdt_attributes
                .iter()
                .map(|esdt_attribute| esdt_attribute.ty.clone()),
        );

        while let Some(type_name) = queue.pop_front() {
            for abi_name in self.top_level_abi_candidates(&type_name) {
                if reachable.contains(&abi_name) {
                    continue;
                }
                let Some(desc) = self.proxy_config.abi.type_descriptions.find(&abi_name) else {
                    continue;
                };
                if !desc.contents.is_specified() {
                    continue;
                }
                if self.path_rename_for(&abi_name, &desc.names.rust).is_some() {
                    continue; // redirected elsewhere - don't emit, don't descend into its fields
                }

                reachable.insert(abi_name);
                queue.extend(Self::field_type_names(&desc.contents));
            }
        }

        reachable
    }

    /// The `abi_rust` type name of every field directly nested in a struct/enum's contents (both
    /// variant tuple and struct-style fields), fed back into `reachable_local_abi_names`'s queue.
    fn field_type_names(contents: &TypeContents) -> Vec<String> {
        match contents {
            TypeContents::Struct(fields) => fields
                .iter()
                .map(|f| f.field_type.abi_rust.clone())
                .collect(),
            TypeContents::Enum(variants) => variants
                .iter()
                .flat_map(|variant| &variant.fields)
                .map(|f| f.field_type.abi_rust.clone())
                .collect(),
            TypeContents::ExplicitEnum(_) | TypeContents::NotSpecified => Vec::new(),
        }
    }

    /// Extracts the bare names of every type embedded in a rust-ish type name (itself, if it's a
    /// plain reference, or each of its generic parameters if it's a composite like
    /// `Option<Kitty>` or `MultiValueEncoded<Kitty>`) as candidate locally-described type names to
    /// feed into `reachable_local_abi_names`'s traversal - mirroring the same path-extraction
    /// `clean_local_paths` uses to resolve those references when actually writing them out. Also
    /// works on a bare bracketed ABI `TypeName` string (event inputs, `#[esdt_attribute]` types),
    /// which uses the same `<>,` composite syntax.
    fn top_level_abi_candidates(&self, type_name: &str) -> Vec<String> {
        extract_paths(type_name)
            .iter()
            .map(|path| path.rsplit("::").next().unwrap_or(path).to_string())
            .collect()
    }

    fn write_enum(
        &mut self,
        enum_variants: &[EnumVariantDescription],
        type_description: &TypeDescription,
        name: &str,
    ) {
        if self.enum_contains_struct_variant(enum_variants) {
            self.write("\n#[rustfmt::skip]");
            if let Some(c_type) = c_enum_representation(enum_variants) {
                self.write(format!("\n#[repr({c_type})]"));
            }
        }

        self.write_macro_attributes(&type_description.macro_attributes);
        self.write(format!("pub enum {name}"));

        if enum_variants.is_empty() {
            self.writeln(" {}");
            return;
        }

        self.writeln(" {");
        for (i, variant) in enum_variants.iter().enumerate() {
            self.write(format!("    {}", variant.name));
            let discriminant = explicit_discriminant(i, variant, enum_variants);

            if variant.fields.is_empty() {
                if discriminant.is_some() {
                    self.write(format!(" = {}", variant.discriminant));
                }
                self.writeln(",");
                continue;
            }

            if variant.fields[0].name == ZERO {
                self.write_tuple_fields(&variant.fields, discriminant, ',');
            } else {
                self.write_struct_variant_fields(&variant.fields, discriminant);
            }
        }
        self.writeln("}");
    }

    fn write_struct(
        &mut self,
        struct_fields: &[StructFieldDescription],
        type_description: &TypeDescription,
        name: &str,
    ) {
        self.write_macro_attributes(&type_description.macro_attributes);
        self.write(format!("pub struct {name}"));

        if struct_fields.is_empty() {
            self.writeln(" {}");
            return;
        }

        if struct_fields.len() == 1 && struct_fields[0].name == ZERO {
            self.write_tuple_fields(struct_fields, None, ';');
            return;
        }

        self.writeln(" {");
        for field in struct_fields {
            let field_type = self.abi_type(&field.field_type);
            self.writeln(format!("    pub {}: {field_type},", field.name));
        }
        self.writeln("}");
    }

    fn write_tuple_fields(
        &mut self,
        fields: &[StructFieldDescription],
        discriminant: Option<usize>,
        punctuation: char,
    ) {
        self.write("(");
        for (i, field) in fields.iter().enumerate() {
            if i > 0 {
                self.write(", ");
            }
            self.write(self.abi_type(&field.field_type));
        }
        match discriminant {
            Some(d) => self.write(format!(") = {d}{punctuation}")),
            None => self.writeln(format!("){punctuation}")),
        }
    }

    fn write_struct_variant_fields(
        &mut self,
        fields: &[StructFieldDescription],
        discriminant: Option<usize>,
    ) {
        self.writeln(" {");
        for field in fields {
            let field_type = self.abi_type(&field.field_type);
            self.writeln(format!("        {}: {field_type},", field.name));
        }
        self.write("    }");
        if let Some(d) = discriminant {
            self.write(format!(" = {d}"));
        }
        self.writeln(",");
    }

    /// Unlike `ProxyGenerator` (which reconstructs real, encodable managed types and so keeps
    /// the original `TopEncode`/`TopDecode`/`Clone`/`Debug`/... derives), these local
    /// definitions only ever compose pure ABI marker types (`BigUintAbi`, `Address`,
    /// `ListAbi<T>`, ...), which themselves derive *nothing* beyond `TypeAbi` — they're never
    /// instantiated, only used as type-level markers (e.g. `ProxyArg<BigUintAbi>`). `TypeAbi`
    /// has no `TopEncode`/`Clone`/etc. bound, so `#[type_abi]` alone is both sufficient and the
    /// only thing that would actually compile here.
    fn write_macro_attributes(&mut self, macro_attributes: &[String]) {
        self.writeln("");
        for attr in macro_attributes {
            if attr.contains("::") {
                self.writeln(format!("#[{attr}]"));
            }
        }
        self.writeln("#[type_abi]");
    }

    fn enum_contains_struct_variant(&self, enum_variants: &[EnumVariantDescription]) -> bool {
        enum_variants
            .iter()
            .any(|variant| !variant.fields.is_empty() && variant.fields[0].name != ZERO)
    }
}
