// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            6
// Async Callback (empty):               1
// Total number of exported functions:   9

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    scenario_tester
    (
        init => init
        upgrade => upgrade
        getSum => sum
        add => add
        multi_param => multi_param
        multi_return => multi_return
        sc_panic => sc_panic
        mul_floats => mul_floats
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
