// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            9
// Async Callback (empty):               1
// Total number of exported functions:  11

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    digital_cash
    (
        init => init
        claimFees => claim_fees
        getAmount => get_amount
        pay_fee_and_fund => pay_fee_and_fund
        fund => fund
        depositFees => deposit_fees
        withdraw => withdraw
        claim => claim
        forward => forward
        deposit => deposit
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
