pub(super) static ATTR_PAYABLE: &str = "payable";
pub(super) static ATTR_ONLY_OWNER: &str = "only_owner";
pub(super) static ATTR_ONLY_ADMIN: &str = "only_admin";
pub(super) static ATTR_ONLY_USER_ACCOUNT: &str = "only_user_account";
pub(super) static ATTR_OUTPUT_NAME: &str = "output_name";
pub(super) static ATTR_PAYMENT: &str = "payment"; // synonymous with `payment_amount`
pub(super) static ATTR_PAYMENT_AMOUNT: &str = "payment_amount";
pub(super) static ATTR_PAYMENT_TOKEN: &str = "payment_token";
pub(super) static ATTR_PAYMENT_NONCE: &str = "payment_nonce";
pub(super) static ATTR_PAYMENT_MULTI: &str = "payment_multi";
pub(super) static ATTR_INIT: &str = "init";
pub(super) static ATTR_VIEW: &str = "view";
pub(super) static ATTR_EXTERNAL_VIEW: &str = "external_view";
pub(super) static ATTR_EVENT: &str = "event";
pub(super) static ATTR_EVENT_INDEXED: &str = "indexed";
pub(super) static ATTR_ENDPOINT: &str = "endpoint";
pub(super) static ATTR_CALLBACK_DECL: &str = "callback"; // will be renamed to "legacy-callback" at some point
pub(super) static ATTR_CALLBACK_PROMISES_DECL: &str = "promises_callback"; // will be renamed to just "callback" at some point
pub(super) static ATTR_CALLBACK_RAW_DECL: &str = "callback_raw";
pub(super) static ATTR_CALLBACK_CALL_RESULT: &str = "call_result";
pub(super) static ATTR_STORAGE_GET: &str = "storage_get";
pub(super) static ATTR_STORAGE_SET: &str = "storage_set";
pub(super) static ATTR_STORAGE_MAPPER: &str = "storage_mapper";
pub(super) static ATTR_STORAGE_IS_EMPTY: &str = "storage_is_empty";
pub(super) static ATTR_STORAGE_CLEAR: &str = "storage_clear";
pub(super) static ATTR_PROXY: &str = "proxy";
pub(super) static ATTR_LABEL: &str = "label";
