use crate::TxContext;
use elrond_wasm::api::LogApi;

/// Interface to only be used by code generated by the macros.
/// The smart contract code doesn't have access to these methods directly.
impl LogApi for TxContext {
	fn write_log(&self, _topics: &[[u8; 32]], _data: &[u8]) {
		// does nothing yet
		// TODO: implement at some point
	}
}
