// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Number of endpoints: 3

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    second_contract
    (
        acceptEsdtPayment
        rejectEsdtPayment
        getesdtTokenName
    )
}

elrond_wasm_node::wasm_empty_callback! {}
