// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]

use multiversx_sc::proxy_imports::*;

pub struct DigitalCashProxy;

impl<Env, From, To, Gas> TxProxyTrait<Env, From, To, Gas> for DigitalCashProxy
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    type TxProxyMethods = DigitalCashProxyMethods<Env, From, To, Gas>;

    fn proxy_methods(self, tx: Tx<Env, From, To, (), Gas, (), ()>) -> Self::TxProxyMethods {
        DigitalCashProxyMethods { wrapped_tx: tx }
    }
}

pub struct DigitalCashProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    wrapped_tx: Tx<Env, From, To, (), Gas, (), ()>,
}

#[rustfmt::skip]
impl<Env, From, Gas> DigitalCashProxyMethods<Env, From, (), Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    Gas: TxGas<Env>,
{
    pub fn init<
        Arg0: ProxyArg<bool>,
        Arg1: ProxyArg<MultiValueEncoded<Env::Api, MultiValue2<TokenId<Env::Api>, BigUint<Env::Api>>>>,
    >(
        self,
        fees_disabled: Arg0,
        fee_variants: Arg1,
    ) -> TxTypedDeploy<Env, From, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_deploy()
            .argument(&fees_disabled)
            .argument(&fee_variants)
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> DigitalCashProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn set_fees_disabled<
        Arg0: ProxyArg<bool>,
    >(
        self,
        fees_disabled: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("setFeesDisabled")
            .argument(&fees_disabled)
            .original_result()
    }

    /// Updates the fee for a specific token. 
    ///  
    /// Setting the fee_amount to zero effectively disables fees for that token. 
    pub fn set_fee<
        Arg0: ProxyArg<TokenId<Env::Api>>,
        Arg1: ProxyArg<BigUint<Env::Api>>,
    >(
        self,
        fee_token: Arg0,
        fee_amount: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("setFee")
            .argument(&fee_token)
            .argument(&fee_amount)
            .original_result()
    }

    pub fn claim_fees(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("claimFees")
            .original_result()
    }

    /// Pays the required fee and funds a deposit for the given address with specified expiration time. 
    pub fn pay_fee_and_fund<
        Arg0: ProxyArg<ManagedByteArray<Env::Api, 32usize>>,
        Arg1: ProxyArg<TimestampMillis>,
    >(
        self,
        deposit_key: Arg0,
        expiration: Arg1,
    ) -> TxTypedCall<Env, From, To, (), Gas, ()> {
        self.wrapped_tx
            .raw_call("payFeeAndFund")
            .argument(&deposit_key)
            .argument(&expiration)
            .original_result()
    }

    pub fn fund<
        Arg0: ProxyArg<ManagedByteArray<Env::Api, 32usize>>,
        Arg1: ProxyArg<TimestampMillis>,
    >(
        self,
        deposit_key: Arg0,
        expiration: Arg1,
    ) -> TxTypedCall<Env, From, To, (), Gas, ()> {
        self.wrapped_tx
            .raw_call("fund")
            .argument(&deposit_key)
            .argument(&expiration)
            .original_result()
    }

    pub fn deposit_fees<
        Arg0: ProxyArg<ManagedByteArray<Env::Api, 32usize>>,
    >(
        self,
        deposit_key: Arg0,
    ) -> TxTypedCall<Env, From, To, (), Gas, ()> {
        self.wrapped_tx
            .raw_call("depositFees")
            .argument(&deposit_key)
            .original_result()
    }

    pub fn withdraw_expired<
        Arg0: ProxyArg<ManagedByteArray<Env::Api, 32usize>>,
    >(
        self,
        deposit_key: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("withdrawExpired")
            .argument(&deposit_key)
            .original_result()
    }

    /// The recipient claims the deposit by providing a valid signature over the deposit key. 
    pub fn claim<
        Arg0: ProxyArg<ManagedByteArray<Env::Api, 32usize>>,
        Arg1: ProxyArg<ManagedByteArray<Env::Api, 64usize>>,
    >(
        self,
        deposit_key: Arg0,
        signature: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("claim")
            .argument(&deposit_key)
            .argument(&signature)
            .original_result()
    }

    pub fn forward<
        Arg0: ProxyArg<ManagedByteArray<Env::Api, 32usize>>,
        Arg1: ProxyArg<ManagedByteArray<Env::Api, 32usize>>,
        Arg2: ProxyArg<ManagedByteArray<Env::Api, 64usize>>,
    >(
        self,
        deposit_key: Arg0,
        forward_deposit_key: Arg1,
        signature: Arg2,
    ) -> TxTypedCall<Env, From, To, (), Gas, ()> {
        self.wrapped_tx
            .raw_call("forward")
            .argument(&deposit_key)
            .argument(&forward_deposit_key)
            .argument(&signature)
            .original_result()
    }

    pub fn deposit<
        Arg0: ProxyArg<ManagedByteArray<Env::Api, 32usize>>,
    >(
        self,
        deposit_key: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, DepositInfo<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("deposit")
            .argument(&deposit_key)
            .original_result()
    }
}

#[type_abi]
#[derive(NestedEncode, NestedDecode, TopEncode, TopDecode)]
pub struct DepositInfo<Api>
where
    Api: ManagedTypeApi,
{
    pub depositor_address: ManagedAddress<Api>,
    pub funds: ManagedVec<Api, Payment<Api>>,
    pub expiration: TimestampMillis,
    pub fees: Option<FungiblePayment<Api>>,
}
