// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]

use multiversx_sc::proxy_imports::*;

pub struct KittyGeneticAlgProxy;

impl<Env, From, To, Gas> TxProxyTrait<Env, From, To, Gas> for KittyGeneticAlgProxy
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    type TxProxyMethods = KittyGeneticAlgProxyMethods<Env, From, To, Gas>;

    fn proxy_methods(self, tx: Tx<Env, From, To, (), Gas, (), ()>) -> Self::TxProxyMethods {
        KittyGeneticAlgProxyMethods { wrapped_tx: tx }
    }
}

pub struct KittyGeneticAlgProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    wrapped_tx: Tx<Env, From, To, (), Gas, (), ()>,
}

#[rustfmt::skip]
impl<Env, From, Gas> KittyGeneticAlgProxyMethods<Env, From, (), Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    Gas: TxGas<Env>,
{
    pub fn init(
        self,
    ) -> TxTypedDeploy<Env, From, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_deploy()
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> KittyGeneticAlgProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn generate_kitty_genes<
        Arg0: ProxyArg<kitty::Kitty>,
        Arg1: ProxyArg<kitty::Kitty>,
    >(
        self,
        matron: Arg0,
        sire: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, kitty::KittyGenes> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("generateKittyGenes")
            .argument(&matron)
            .argument(&sire)
            .original_result()
    }
}
