name = "storage-examples"
contract_trait = "StorageExamples"
src_file = "storage_examples.rs"
rename_pairs = []
files_include = [
    "meta",
    "scenarios",
    "src",
    "tests",
    "wasm/Cargo.lock",
    "Cargo.toml",
    "multiversx.json",
    "README.md",
    "sc-config.toml",
]
