/// Arguments to `#[multiversx_sc::contract(...)]`.
///
/// - `call = ProxyName`: see `proxy_gen::ProxyCallArg` (same meaning, shared parsing style).
/// - `implements_abi = Path` (repeatable): the contract's ABI must contain every export declared by
///   the referenced ABI spec (a type implementing `multiversx_sc_abi::ContractAbiProvider`,
///   typically the `AbiProvider` generated by a `#[contract_abi]`-annotated trait elsewhere).
///   The contract may have additional exports beyond the spec.
/// - `implements_abi_exactly = Path` (repeatable): like `implements_abi`, but the contract's export set
///   must equal the spec's exactly, with no additional exports.
///
/// Both `implements_abi` and `implements_abi_exactly` only record the referenced spec on the contract's
/// own `ContractAbi` (`implements_abi`/`implements_abi_exactly` fields); actual conformance checking
/// happens later, in the meta crate (`framework/meta-lib`'s `abi_conformance` module).
#[derive(Default)]
pub struct ContractMacroArgs {
    pub call: Option<syn::Ident>,
    pub implements_abi: Vec<syn::Path>,
    pub implements_abi_exactly: Vec<syn::Path>,
}

enum ContractMacroArg {
    Call(syn::Ident),
    Implements(syn::Path),
    ImplementsExactly(syn::Path),
}

impl syn::parse::Parse for ContractMacroArg {
    fn parse(input: syn::parse::ParseStream) -> syn::Result<Self> {
        let key: syn::Ident = input.parse()?;
        input.parse::<syn::Token![=]>()?;

        if key == "call" {
            Ok(ContractMacroArg::Call(input.parse()?))
        } else if key == "implements_abi" {
            Ok(ContractMacroArg::Implements(input.parse()?))
        } else if key == "implements_abi_exactly" {
            Ok(ContractMacroArg::ImplementsExactly(input.parse()?))
        } else {
            Err(syn::Error::new(
                key.span(),
                "expected `call`, `implements_abi` or `implements_abi_exactly`",
            ))
        }
    }
}

impl syn::parse::Parse for ContractMacroArgs {
    fn parse(input: syn::parse::ParseStream) -> syn::Result<Self> {
        let args =
            syn::punctuated::Punctuated::<ContractMacroArg, syn::Token![,]>::parse_terminated(
                input,
            )?;

        let mut result = ContractMacroArgs::default();
        for arg in args {
            match arg {
                ContractMacroArg::Call(proxy_name) => result.call = Some(proxy_name),
                ContractMacroArg::Implements(path) => result.implements_abi.push(path),
                ContractMacroArg::ImplementsExactly(path) => {
                    result.implements_abi_exactly.push(path)
                }
            }
        }

        Ok(result)
    }
}
