// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Number of endpoints: 8

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    nft_storage_prepay
    (
        setCostPerByte
        reserveFunds
        claim
        depositPaymentForStorage
        withdraw
        getCostForSize
        getDepositAmount
        getCostPerByte
    )
}

elrond_wasm_node::wasm_empty_callback! {}
