// Code generated by the mx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            8
// Async Callback (empty):               1
// Total number of exported functions:  10

#![no_std]

mx_sc_wasm_adapter::external_view_wasm_endpoints! {
    multisig
    (
        getPendingActionFullInfo
        userRole
        getAllBoardMembers
        getAllProposers
        getActionData
        getActionSigners
        getActionSignerCount
        getActionValidSignerCount
    )
}

mx_sc_wasm_adapter::wasm_empty_callback! {}
