////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    alloc_features
    (
        boxed_bytes_concat_2
        boxed_bytes_split
        boxed_bytes_zeros
        compare_h256
        compute_create_ec
        compute_ec_add
        compute_ec_double
        compute_generate_key_ec
        compute_get_ec_length
        compute_get_priv_key_byte_length
        compute_get_values
        compute_is_on_curve_ec
        compute_keccak256_legacy_alloc
        compute_marshal_compressed_ec
        compute_marshal_ec
        compute_ripemd160
        compute_scalar_base_mult
        compute_scalar_mult
        compute_secp256k1_der_signature
        compute_sha256_legacy_alloc
        compute_unmarshal_compressed_ec
        compute_unmarshal_ec
        echo_async_result_empty
        echo_big_int_vec
        echo_boxed_array_u8
        echo_boxed_bytes
        echo_boxed_ser_example_1
        echo_h256
        echo_large_boxed_byte_array
        echo_multi_value_tuples
        echo_ser_example_1
        echo_slice_u8
        echo_str
        echo_str_box
        echo_string
        echo_varags_big_uint
        echo_varags_u32
        echo_vec_of_managed_buffer
        echo_vec_u8
        h256_is_zero
        is_empty_opt_addr
        load_addr
        load_opt_addr
        load_ser_1
        load_vec_u8
        logLegacyEventA
        logLegacyEventB
        managed_address_from
        mbuffer_append_bytes
        mbuffer_from_boxed_bytes
        mbuffer_from_slice
        mbuffer_load_slice
        mbuffer_overwrite
        mbuffer_set_slice
        only_owner_legacy
        result_echo
        result_echo_2
        result_echo_3
        result_err_from_bytes_1
        result_err_from_bytes_2
        result_err_from_bytes_3
        result_err_from_str
        result_err_from_string
        result_ok
        return_sc_error
        store_addr
        store_opt_addr
        store_ser_1
        store_vec_u8
        vec_concat_const
        verify_bls_signature
        verify_custom_secp256k1_signature
        verify_ed25519_signature
        verify_secp256k1_signature
    )
}

elrond_wasm_node::wasm_empty_callback! {}
