// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            5
// Async Callback (empty):               1
// Total number of exported functions:   7

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    managed_map_features
    (
        init => init
        mm_put => mm_put
        mm_remove => mm_remove
        mm_get => mm_get
        mm_contains => mm_contains
        mm_remove_get => mm_remove_get
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
