[package]
name = "kitty-genetic-alg"
version = "0.0.0"
authors = [ "dorin-iancu <dorin.iancu@multiversx.com>",]
edition = "2024"
publish = false

[lib]
path = "src/lib.rs"


[dependencies.kitty-abi]
version = "0.0.0"
path = "../abi"

[dependencies.random]
version = "0.0.0"
path = "../random"

[dependencies.multiversx-sc]
workspace = true

[dev-dependencies.multiversx-sc-scenario]
workspace = true
