// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           10
// Async Callback (empty):               1
// Total number of exported functions:  12

#![no_std]

mx_sc_wasm_adapter::wasm_endpoints! {
    ping_pong_egld
    (
        ping
        pong
        pongAll
        getUserAddresses
        getPingAmount
        getDeadline
        getActivationTimestamp
        getMaxFunds
        getUserStatus
        pongAllLastUser
    )
}

mx_sc_wasm_adapter::wasm_empty_callback! {}
