// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            5
// Async Callback (empty):               1
// Total number of exported functions:   7

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    forwarder_barnard
    (
        init => init
        sync_call_fallible => sync_call_fallible
        forward_sync_fallible_accept_funds_multi_transfer => forward_sync_fallible_accept_funds_multi_transfer
        forward_sync_reject_funds_multi_transfer => forward_sync_reject_funds_multi_transfer
        transfer_fallible => transfer_fallible
        transfer_execute_fallible => transfer_execute_fallible
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
