// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            3
// Async Callback (empty):               1
// Total number of exported functions:   5

#![no_std]

multiversx_sc_wasm_adapter::allocator!(static64k);
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    serde_features
    (
        init => init
        out_value_1 => out_value_1
        out_value_1_pretty => out_value_1_pretty
        inc_serde_1 => inc_serde_1
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
