contract_addresses = [
    "erd1qqqqqqqqqqqqqpgqe8jtrfmj5f6jcmn605r5t8950p3wu63gqqqqedcx6q",
    "erd1qqqqqqqqqqqqqpgq5zrl4gg8mvhka724l88gst0r3csscqv6qqqsh8ljxe",
    "erd1qqqqqqqqqqqqqpgqqkq5a4au3t5ydws4y7eq86wwxz8d8pe0qqpqcyl6cg",
]
