// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           10
// Async Callback (empty):               1
// Total number of exported functions:  12

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    bonding_curve_contract
    (
        sellToken
        buyToken
        deposit
        setBondingCurve
        claim
        view_buy_price
        view_sell_price
        getTokenAvailability
        setLocalRoles
        unsetLocalRoles
    )
}

elrond_wasm_node::wasm_empty_callback! {}
