mod op_gen_endpoints;
mod op_gen_scenario;
mod op_list;

pub use op_gen_endpoints::{create_all_endpoints, BigNumOperatorTestEndpoint, ValueType};
pub use op_gen_scenario::write_scenarios;
pub use op_list::{OperatorGroup, OperatorInfo, OperatorList};

use std::fmt::Write;

fn section_comment(out: &mut String, comment: &str) {
    writeln!(out, "\n\n    // {}", comment).unwrap();
}

fn write_filtered_endpoints(
    endpoints: &[BigNumOperatorTestEndpoint],
    op_group: OperatorGroup,
    assign: bool,
    out: &mut String,
) {
    for endpoint in endpoints {
        if endpoint.op_info.group == op_group && endpoint.op_info.assign == assign {
            endpoint.write_endpoint(out);
        }
    }
}

/// Generates a Rust trait similar to BigIntOperators, with methods for each operator in OPS.
pub fn generate_big_int_operators_trait() -> String {
    let mut out = BIG_NUM_OPERATORS_PRELUDE.to_string();
    let ops = OperatorList::create();
    let endpoints = create_all_endpoints(&ops);

    println!("Generated {} endpoints.", endpoints.len());

    section_comment(&mut out, "Arithmetic binary operators");
    write_filtered_endpoints(&endpoints, OperatorGroup::Arithmetic, false, &mut out);

    section_comment(&mut out, "Arithmetic assign operators");
    write_filtered_endpoints(&endpoints, OperatorGroup::Arithmetic, true, &mut out);

    section_comment(&mut out, "Bitwise binary operators");
    write_filtered_endpoints(&endpoints, OperatorGroup::Bitwise, false, &mut out);

    section_comment(&mut out, "Bitwise assign operators");
    write_filtered_endpoints(&endpoints, OperatorGroup::Bitwise, true, &mut out);

    section_comment(&mut out, "Bitwise shift binary operators");
    write_filtered_endpoints(&endpoints, OperatorGroup::Shift, false, &mut out);

    section_comment(&mut out, "Bitwise shift assign operators");
    write_filtered_endpoints(&endpoints, OperatorGroup::Shift, true, &mut out);

    writeln!(&mut out, "\n}}").unwrap();

    out
}

const BIG_NUM_OPERATORS_PRELUDE: &str = r#"// Code generated by tools/op-test-gen crate. DO NOT EDIT.

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!!!!!!!!!!!!!!!!!!!!! AUTO-GENERATED FILE !!!!!!!!!!!!!!!!!!!!!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

multiversx_sc::imports!();

/// Checks that BigUint/BigInt operators work as expected.
#[multiversx_sc::module]
#[rustfmt::skip]
pub trait BigIntOperators {
    // Endpoints grouped into several sections:"#;

pub fn write_big_int_operators_trait() {
    let target_path = "../../contracts/feature-tests/basic-features/src/big_num_operators.rs";
    let content = generate_big_int_operators_trait();
    if let Err(e) = std::fs::write(std::path::Path::new(target_path), content) {
        eprintln!("Failed to write to {}: {}", target_path, e);
        std::process::exit(1);
    } else {
        println!("Successfully rewrote {}", target_path);
    }
}
