[package]
name = "crypto-zombies"
version = "0.0.0"
authors = ["Alin Cruceat <alin.cruceat@multiversx.com>"]
edition = "2024"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.multiversx-sc]
workspace = true

[dependencies.multiversx-sc-abi]
workspace = true

[dependencies.multiversx-sc-abi-derive]
version = "0.25.0"
path = "../../../data/abi-derive"

[dev-dependencies.multiversx-sc-scenario]
workspace = true
