use multiversx_chain_core::std::Bech32Address;
use serde::{Deserialize, Serialize};

use super::log_data::LogData;

// Events represents the events generated by a transaction with changed fields' types in order to make it friendly for API's json
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Events {
    pub address: Bech32Address,
    pub identifier: String,
    #[serde(default)]
    pub topics: Vec<String>,
    #[serde(default)]
    pub data: LogData,
}
