/// Interface to only be used by code generated by the macros.
/// The smart contract code doesn't have access to these methods directly.
pub trait LogApi {
	fn write_log(&self, topics: &[[u8; 32]], data: &[u8]);
}
