// Code generated by the mx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            2
// Async Callback (empty):               1
// Total number of exported functions:   4

#![no_std]

mx_sc_wasm_adapter::wasm_endpoints! {
    erc1155_user_mock
    (
        onERC1155Received
        onERC1155BatchReceived
    )
}

mx_sc_wasm_adapter::wasm_empty_callback! {}
