call_tree_path = "layouts/async_v1_c1_smin_pay.toml"

[gateway]
uri = "https://testnet-gateway.multiversx.com"
chain_type = "real"

# [gateway]
# uri = "https://gateway.battleofnodes.com"
# chain_type = "real"
