call_tree_path = "layouts/sync_a1_sync.toml"
# call_tree_path = "layouts/direct.toml"

[gateway]
uri = "http://localhost:8085"
chain_type = "simulator"

# [gateway]
# uri = "https://testnet-gateway.multiversx.com/"
# chain_type = "real"


