// Code generated by the mx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            6
// Async Callback:                       1
// Total number of exported functions:   8

#![no_std]

mx_sc_wasm_adapter::wasm_endpoints! {
    proxy_test_first
    (
        deploySecondContract
        upgradeSecondContract
        forwardToOtherContract
        forwardToOtherContractWithCallback
        messageOtherContract
        messageOtherContractWithCallback
        callBack
    )
}
