// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Number of endpoints: 6

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    proxy_test_first
    (
        deploySecondContract
        upgradeSecondContract
        forwardToOtherContract
        forwardToOtherContractWithCallback
        messageOtherContract
        messageOtherContractWithCallback
    )
}
