// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            9
// Async Callback:                       1
// Total number of exported functions:  11

#![no_std]
#![feature(alloc_error_handler, lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    kitty_auction
    (
        setKittyOwnershipContractAddress
        createAndAuctionGenZeroKitty
        isUpForAuction
        getAuctionStatus
        getCurrentWinningBid
        createSaleAuction
        createSiringAuction
        bid
        endAuction
        callBack
    )
}
