// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Number of endpoints: 0

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    empty
    (
    )
}

elrond_wasm_node::wasm_empty_callback! {}
