// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            5
// Async Callback:                       1
// Promise callbacks:                    1
// Total number of exported functions:   8

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    forwarder_net
    (
        init => init
        id => id
        queued_calls => queued_calls
        trace => trace
        set_queued_calls => set_queued_calls
        bump => bump
        async_v2_callback => async_v2_callback
    )
}

multiversx_sc_wasm_adapter::async_callback! { forwarder_net }
