// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Number of endpoints: 9

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    seed_nft_minter
    (
        callBack
        createNft
        claimAndDistribute
        getMarketplaces
        getNftCount
        getDistributionRules
        issueToken
        buyNft
        getNftPrice
        getNftTokenId
    )
}
