// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]

use multiversx_sc_abi::imports::*;

#[rustfmt::skip]
#[multiversx_sc_abi::contract_abi(call = VaultUpgradeCall)]
pub trait Vault {
    #[upgrade]
    fn upgrade(&self, opt_arg_to_echo: OptionalValue<BytesAbi>) -> MultiValue2<StringAbi, OptionalValue<BytesAbi>>;

}
