// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Number of endpoints: 6

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    nft_minter
    (
        callBack
        createNft
        claimRoyaltiesFromMarketplace
        issueToken
        setLocalRoles
        buyNft
        getNftPrice
    )
}
