// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Number of endpoints: 20

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    multisig
    (
        deposit
        signed
        sign
        unsign
        discardAction
        getQuorum
        getNumBoardMembers
        getNumProposers
        getActionLastIndex
        proposeAddBoardMember
        proposeAddProposer
        proposeRemoveUser
        proposeChangeQuorum
        proposeTransferExecute
        proposeAsyncCall
        proposeSCDeployFromSource
        proposeSCUpgradeFromSource
        quorumReached
        performAction
        dnsRegister
    )
}

elrond_wasm_node::wasm_empty_callback! {}
