[gateway]
uri = "https://testnet-gateway.multiversx.com"
chain_type = "real"

[[start]]
to = 0
gas_limit = 70000000

[[contracts]]
index = 0
name = "root"
address = "erd1qqqqqqqqqqqqqpgq37h7dksmyy5373rdeaz3v6ucql4za99ln54q23xnxg"

[[contracts.children]]
to = 1
call_type = "legacy_async"
gas_limit = 10000000

[[contracts]]
index = 1
name = "leaf"
address = "erd1qqqqqqqqqqqqqpgq6z9ws38g5wud3pvtrp4f3atqrpslxqnzn54qmdykf6"
