[gateway]
uri = "https://testnet-gateway.multiversx.com"
chain_type = "real"

[[start]]
to = 0
gas_limit = 70000000

[[contracts]]
index = 0
name = "root"
address = "erd1qqqqqqqqqqqqqpgq4wx6m0x64hhrfwlaa84g7w9wyv32msxyn54q6zfph2"

[[contracts.children]]
to = 1
call_type = "legacy_async"
gas_limit = 10000000

[[contracts]]
index = 1
name = "leaf"
address = "erd1qqqqqqqqqqqqqpgqn6q65sut5rntu342023c366l97gjhf7gn54qhgy5qv"
