[gateway]
uri = "https://testnet-gateway.multiversx.com"
chain_type = "real"

[[contracts]]
index = 0
name = "root"
kind = "forwarder"

[[contracts.children]]
to = 1
call_type = "legacy_async"
gas_limit = 10000000
endpoint_name = "accept_funds"

[[contracts]]
index = 1
name = "vault"
kind = "vault"
