// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Number of endpoints: 1

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    kitty_genetic_alg
    (
        generateKittyGenes
    )
}

elrond_wasm_node::wasm_empty_callback! {}
