// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            5
// Async Callback (empty):               1
// Total number of exported functions:   7

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    barnard_features
    (
        init => init
        epochInfo => epoch_info
        codeHash => code_hash
        get_block_timestamps => get_block_timestamps
        get_block_timestamp_ms => get_block_timestamp_ms
        get_prev_block_timestamp_ms => get_prev_block_timestamp_ms
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
