// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]

use multiversx_sc::abi::*;
use multiversx_sc::derive_imports::*;
use multiversx_sc::imports::*;
use multiversx_sc_abi_derive::contract_abi;

#[type_abi]
pub struct OnlyShowsUpInConstructor {
    pub something: (),
}

#[type_abi]
pub struct AbiTestType {
    pub nested: OnlyShowsUpAsNested01,
    pub next: Option<Box<AbiTestType>>,
    pub tuple_madness: (OnlyShowsUpAsNested02, Option<Box<AbiTestType>>),
}

#[type_abi]
pub struct OnlyShowsUpAsNested01 {}

#[type_abi]
pub struct OnlyShowsUpAsNested02 {
    pub something: [u8; 0],
}

#[rustfmt::skip]
#[type_abi]
pub enum AbiEnum {
    Nothing,
    Something(i32),
    SomethingMore(u8, OnlyShowsUpAsNested08),
    SomeStruct {
        a: u16,
        b: OnlyShowsUpAsNested09,
    },
}

#[type_abi]
pub struct OnlyShowsUpAsNested08 {}

#[type_abi]
pub struct OnlyShowsUpAsNested09 {}

#[type_abi]
pub struct AbiManagedType {
    pub big_uint: BigUintAbi,
    pub integer: i32,
    pub managed_buffer: ListAbi<u8>,
}

#[type_abi]
pub struct OnlyShowsUpAsNested03 {}

#[type_abi]
pub struct OnlyShowsUpAsNested04 {}

#[type_abi]
pub struct OnlyShowsUpAsNested05 {}

#[type_abi]
pub struct OnlyShowsUpAsNested06 {}

#[type_abi]
pub struct OnlyShowsUpAsNested07 {}

#[type_abi]
pub enum EsdtLocalRole {
    None,
    Mint,
    Burn,
    NftCreate,
    NftAddQuantity,
    NftBurn,
    NftAddUri,
    NftUpdateAttributes,
    Transfer,
}

#[type_abi]
pub struct EsdtTokenPayment {
    pub token_identifier: EsdtTokenIdentifierAbi,
    pub token_nonce: u64,
    pub amount: BigUintAbi,
}

#[type_abi]
pub struct EsdtTokenData {
    pub token_type: EsdtTokenType,
    pub amount: BigUintAbi,
    pub frozen: bool,
    pub hash: ListAbi<u8>,
    pub name: ListAbi<u8>,
    pub attributes: ListAbi<u8>,
    pub creator: AddressAbi,
    pub royalties: BigUintAbi,
    pub uris: ListAbi<ListAbi<u8>>,
}

#[type_abi]
pub enum EsdtTokenType {
    Fungible,
    NonFungible,
    SemiFungible,
    Meta,
    Invalid,
}

#[type_abi]
pub struct OnlyShowsUpAsNestedInSingleValueMapper {}

#[type_abi]
pub struct OnlyShowsUpAsNestedInVec {}

#[type_abi]
pub struct OnlyShowsUpAsNestedInArrayVec {}

#[type_abi]
pub struct AbiManagedVecItem {
    pub value1: u32,
    pub value2: u32,
}

#[type_abi]
pub struct Permission(u32);

#[type_abi]
pub struct OnlyShowsUpAsNestedInArray {}

#[type_abi]
pub struct OnlyShowsUpAsNestedInBox {}

#[type_abi]
pub struct OnlyShowsUpAsNestedInBoxedSlice {}

#[type_abi]
pub struct OnlyShowsUpAsNestedInRef {}

#[type_abi]
pub struct OnlyShowsUpAsNestedInSlice {}

#[type_abi]
pub struct OnlyShowsUpAsNestedInOption {}

#[type_abi]
pub struct AbiWithManagedBufferReadToEnd {
    pub endpoint: ListAbi<u8>,
    pub gas: u64,
    pub flush: BytesReadToEndAbi,
}

#[type_abi]
pub struct OnlyShowsUpInEsdtAttr {
    pub field: OnlyShowsUpAsNested10,
}

#[type_abi]
pub struct OnlyShowsUpAsNested10 {}

#[type_abi]
pub enum ExplicitDiscriminant {
    Zero,
    Thirty = 30,
    Twelve = 12,
    Fifty = 50,
    FiftyOne,
}

#[rustfmt::skip]
#[repr(u8)]
#[type_abi]
pub enum ExplicitDiscriminantMixed {
    Zero,
    Unit = 3,
    Tuple(u16),
    Five,
    Struct {
        a: u8,
        b: u16,
    } = 1,
}

#[type_abi]
pub struct ManagedDecimalWrapper {
    pub field: DecimalConstAbi<U2>,
}

#[rustfmt::skip]
#[contract_abi(call = AbiTesterCall)]
pub trait AbiTester {
    /// Contract constructor.
    #[payable("EGLD")]
    #[init]
    fn init(&self, _constructor_arg_1: i32, _constructor_arg_2: OnlyShowsUpInConstructor);

    /// Upgrade constructor.
    #[upgrade]
    fn upgrade(&self, _constructor_arg_1: i32, _constructor_arg_2: OnlyShowsUpInConstructor);

    /// Example endpoint docs.
    #[endpoint(echo_abi_test_type)]
    fn echo_abi_test_type(&self, att: AbiTestType) -> AbiTestType;

    #[only_owner]
    #[endpoint(echo_enum)]
    fn echo_enum(&self, e: AbiEnum) -> AbiEnum;

    #[only_owner]
    #[endpoint(take_managed_type)]
    fn take_managed_type(&self, _arg: AbiManagedType);

    #[endpoint(multi_result_3)]
    fn multi_result_3(&self) -> MultiValue3<i32, [u8; 3], BoxedBytes>;

    #[endpoint(multi_result_4)]
    fn multi_result_4(&self) -> MultiValue4<i32, [u8; 3], BoxedBytes, OnlyShowsUpAsNested03>;

    #[endpoint(var_args)]
    fn var_args(&self, _simple_arg: u32, _var_args: MultiValueVec<MultiValue2<OnlyShowsUpAsNested04, i32>>);

    #[endpoint(multi_result_vec)]
    fn multi_result_vec(&self) -> MultiValueVec<MultiValue3<OnlyShowsUpAsNested05, bool, ()>>;

    #[endpoint(optional_arg)]
    fn optional_arg(&self, _simple_arg: u32, _opt_args: OptionalValue<OnlyShowsUpAsNested06>);

    #[endpoint(optional_result)]
    fn optional_result(&self) -> OptionalValue<OnlyShowsUpAsNested07>;

    #[endpoint(address_vs_h256)]
    fn address_vs_h256(&self, address: AddressAbi, h256: H256) -> MultiValue2<AddressAbi, H256>;

    #[endpoint(managed_address_vs_byte_array)]
    fn managed_address_vs_byte_array(&self, address: AddressAbi, byte_array: [u8; 32]) -> MultiValue2<AddressAbi, [u8; 32]>;

    #[endpoint(process_managed_decimal)]
    fn process_managed_decimal(&self, input: DecimalConstAbi<U10>) -> DecimalAbi;

    #[endpoint(esdt_local_role)]
    fn esdt_local_role(&self) -> EsdtLocalRole;

    #[endpoint(esdt_token_payment)]
    fn esdt_token_payment(&self) -> EsdtTokenPayment;

    #[endpoint(esdt_token_data)]
    fn esdt_token_data(&self) -> EsdtTokenData;

    #[endpoint(time_types)]
    fn time_types(&self) -> MultiValue4<TimestampMillis, TimestampSeconds, DurationMillis, DurationSeconds>;

    #[view(sample_storage_mapper)]
    fn sample_storage_mapper(&self) -> OnlyShowsUpAsNestedInSingleValueMapper;

    #[view(item_for_vec)]
    fn item_for_vec(&self) -> Vec<OnlyShowsUpAsNestedInVec>;

    #[view(item_for_array_vec)]
    fn item_for_array_vec(&self) -> ArrayVec<OnlyShowsUpAsNestedInArrayVec, 3usize>;

    #[view(item_for_managed_vec)]
    fn item_for_managed_vec(&self) -> ListAbi<AbiManagedVecItem>;

    #[view(echo_permission)]
    fn echo_permission(&self, p: Permission) -> Permission;

    #[view(item_for_array)]
    fn item_for_array(&self, _array: [OnlyShowsUpAsNestedInArray; 5]);

    #[view(item_for_box)]
    fn item_for_box(&self) -> OnlyShowsUpAsNestedInBox;

    #[view(item_for_boxed_slice)]
    fn item_for_boxed_slice(&self) -> Box<[OnlyShowsUpAsNestedInBoxedSlice]>;

    #[view(item_for_ref)]
    fn item_for_ref(&self, _ref: OnlyShowsUpAsNestedInRef);

    #[view(item_for_slice)]
    fn item_for_slice(&self, _ref: Vec<OnlyShowsUpAsNestedInSlice>);

    #[view(item_for_option)]
    fn item_for_option(&self) -> Option<OnlyShowsUpAsNestedInOption>;

    #[view(operation_completion_status)]
    fn operation_completion_status(&self) -> OperationCompletionStatus;

    #[view(takes_object_with_managed_buffer_read_to_end)]
    fn takes_object_with_managed_buffer_read_to_end(&self, arg: AbiWithManagedBufferReadToEnd) -> ListAbi<u8>;

    #[payable("EGLD")]
    #[endpoint(payable_egld)]
    fn payable_egld(&self);

    #[payable("TOKEN-FOR-ABI")]
    #[endpoint(payable_some_token)]
    fn payable_some_token(&self);

    #[payable("*")]
    #[endpoint(payable_any_token)]
    fn payable_any_token(&self);

    #[endpoint(external_view)]
    fn external_view(&self);

    #[endpoint(label_a)]
    fn label_a(&self);

    #[endpoint(label_b)]
    fn label_b(&self);

}
