name: sc-meta CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  checks: write
  pull-requests: write

jobs:
  template_test_current:
    name: Template tool test - current (unreleased) templates
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.87
          target: wasm32v1-none

      - name: Install prerequisites
        run: |
          cargo install wasm-opt
          cargo install --path framework/meta
          sc-meta install mx-scenario-go --tag v5.1.0

          which wasm-opt
          which mx-scenario-go
          mx-scenario-go --version

      - name: Run template tool test
        run: |
          cd framework/meta
          cargo test --features template-test-current

  template_test_released:
    name: Template tool test - released templates
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.87
          target: wasm32-unknown-unknown

      - name: Install prerequisites
        run: |
          cargo install wasm-opt
          cargo install --path framework/meta
          sc-meta install mx-scenario-go --tag v5.1.0
          sc-meta install wasm32

          which wasm-opt
          which mx-scenario-go
          mx-scenario-go --version

      - name: Run template tool test
        run: |
          cd framework/meta
          cargo test --features template-test-released

  sc_meta_tx_cli_chain_simulator_tests:
    name: sc-meta tx CLI chain simulator tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.95

      - name: Install sc-meta
        env:
          RUSTFLAGS: ""
        run: cargo install --path framework/meta

      - name: Pull latest chain simulator docker image
        env:
          RUSTFLAGS: ""
        run: sc-meta cs install

      - name: Run sc-meta tx CLI tests
        env:
          RUSTFLAGS: ""
        run: |
          sc-meta cs start &

          sleep 5

          cd framework/meta
          cargo test --features chain-simulator-tests || TEST_RESULT=$?

          sc-meta cs stop

          exit ${TEST_RESULT:-0}

      - name: Cleanup
        if: always()
        run: sc-meta cs stop 2>/dev/null || true