[contracts.main]
name = "vault"
add-unlabelled = true
add-labels = ["upgrade"]

[contracts.upgrade]
name = "vault-upgrade"
add-unlabelled = false
add-labels = ["upgrade"]

[[proxy]]
path = "../recursive-caller/src/vault_proxy.rs"

[[generate-abi]]
path = "../abi/src/vault_abi.rs"
call = "VaultCall"
add-labels = ["upgrade"] # full interface

[[generate-abi]]
path = "../abi/src/vault_upgrade_abi.rs"
add-unlabelled = false
add-labels = ["upgrade"]
call = "VaultUpgradeCall"
